# Generated by Django 3.1.5 on 2021-01-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
