# Generated by Django 3.1.5 on 2021-01-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20210126_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
