# Generated by Django 3.1.5 on 2021-02-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20210203_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='pattern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
