version: '3'

services:
  db:
    restart: always
    image: mysql:8
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_DATABASE: 'sr_app_db'
       MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5

  web:
    restart: unless-stopped
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    tty: true
    build: ./sr_frontend
    volumes:
      - static:/app/sr_frontend/static
      - ./sr_frontend:/app/sr_frontend
      - node-modules:/app/sr_frontend/node_modules
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./config/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/var/www/frontend
    depends_on:
      - web
      - frontend

volumes:
  node-modules:
  static: