version: '3'

services:
  db:
    image: mysql:8
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_DATABASE: 'sr_app_db'
       MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  client:
    build: ./sr_app_client
    command: ["npm", "start"]
    volumes:
      - ./sr_app_client:/app/sr_app_client
      - node-modules:/app/sr_app_client/node_modules
    ports:
      - "3000:3000"
    networks:
      - db-net
      
networks:
  db-net:
    driver: bridge     

volumes:
  node-modules: