version: '3'

services:
  db:
    restart: always
    image: mysql:8
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_DATABASE: 'sr_app_db'
       MYSQL_ROOT_PASSWORD: 'password'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
  web:
    restart: unless-stopped
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    restart: unless-stopped
    build: ./sr_frontend
    command: ["npm", "start"]
    volumes:
      - ./sr_frontend:/app/sr_frontend
      - node-modules:/app/sr_frontend/node_modules
    ports:
      - "3000:3000"
    networks:
      - db-net

networks:
  db-net:
    driver: bridge

volumes:
  node-modules:
